/* -*-  Mode: C++; c-file-style: "gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2007 INRIA
 *               2009,2010 Contributors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Martín Giachino <martin.giachino@gmail.com>
 *
 *
 * This example demonstrates the use of Ns2MobilityHelper class to work with mobility.
 *
 * Detailed example description.
 *
 *  - intended usage: this should be used in order to load ns2 movement trace files into ns3.
 *  - behavior:
 *      - Ns2MobilityHelper object is created, associated to the specified trace file. 
 *      - A log file is created, using the log file name argument.
 *      - A node container is created with the number of nodes specified in the command line.  For the default ns-2 trace, specify the value 2 for this argument.
 *      - the program calls the Install() method of Ns2MobilityHelper to set mobility to nodes. At this moment, the file is read line by line, and the movement is scheduled in the simulator.
 *      - A callback is configured, so each time a node changes its course a log message is printed.
 *  - expected output: example prints out messages generated by each read line from the ns2 movement trace file.
 *                     For each line, it shows if the line is correct, or of it has errors and in this case it will
 *                     be ignored.
 *
 * Usage of ns2-mobility-trace:
 *
 *  ./waf --run "ns2-mobility-trace \
 *        --traceFile=src/mobility/examples/default.ns_movements
 *        --nodeNum=2  --duration=100.0 --logFile=ns2-mobility-trace.log"
 *
 *  NOTE: ns2-traces-file could be an absolute or relative path. You could use the file default.ns_movements
 *        included in the same directory as the example file.
 *  NOTE 2: Number of nodes present in the trace file must match with the command line argument.
 *          Note that you must know it before to be able to load it.
 *  NOTE 3: Duration must be a positive number and should match the trace file. Note that you must know it before to be able to load it.
 */


#include <iostream>
#include <fstream>
#include <sstream>
#include "ns3/core-module.h"
#include "ns3/mobility-module.h"
#include "ns3/ns2-mobility-helper.h"
#include "ns3/netanim-module.h"
// #include "ns3/core-module.h"
#include "ns3/network-module.h"
// #include "ns3/mobility-module.h"
#include "ns3/config-store-module.h"
#include "ns3/wifi-module.h"
#include "ns3/internet-module.h"
// #include "ns3/netanim-module.h"
#include "ns3/ipv4-header.h"
#include "ns3/packet.h"
#include "ns3/tag.h"
#include "ns3/on-off-helper.h"
#include "ns3/snr-tag.h"
#include "ns3/event-id.h"
#include <iostream>
#include <sstream>
#include <fstream>
#include <vector>
#include <string>
#include <cstring>
#include <unistd.h>
#include <map>
#include<stdio.h>
#include <iomanip>
#include<chrono>


using namespace ns3;
using namespace std;


double stnd=450;
// Example to use ns2 traces file in ns3
int main (int argc, char *argv[])
{
  std::string traceFile;
   double duration=300;
  
  std::string logFile;
  int    nodeNum=100;
   int    nodeNum2=4;
  NodeContainer vehicles;
  vehicles.Create (nodeNum);
  NodeContainer rsu;
  rsu.Create (nodeNum2);
  

  MobilityHelper mobility;
mobility.SetPositionAllocator ("ns3::GridPositionAllocator",
"MinX", DoubleValue (0.0),
"MinY", DoubleValue (0.0),
"DeltaX", DoubleValue (5.0),
"DeltaY", DoubleValue (10.0),
"GridWidth", UintegerValue (3),
"LayoutType", StringValue ("RowFirst"));

mobility.SetMobilityModel ("ns3::ConstantPositionMobilityModel");
Ptr<ListPositionAllocator> positionAlloc = CreateObject<ListPositionAllocator> ();
 positionAlloc->Add (Vector (1802,1177, 0.0));
 positionAlloc->Add (Vector (2440.5,1335, 0.0));
 positionAlloc->Add (Vector (2754.5, 1020, 0.0));
 // positionAlloc->Add (Vector (3155, 1570,0.0));
 positionAlloc->Add (Vector (2283.5, 706.5,0.0));
mobility.SetPositionAllocator (positionAlloc);
 mobility.Install (rsu);
  // std::cout<<"Hello"
 
  // Enable logging from the ns2 helper
  LogComponentEnable ("Ns2MobilityHelper",LOG_LEVEL_DEBUG);

  // Parse command line attribute
 
  Ns2MobilityHelper ns2 = Ns2MobilityHelper ("/home/prateek/Downloads/guindy/into/mobility_new.tcl");
  ns2.Install();
  
  // Check command line arguments
  
  // Create Ns2MobilityHelper with the specified trace log file as parameter
 // Ns2MobilityHelper ns2 = Ns2MobilityHelper (traceFile);

  // open log file for output
  
  //while(Simulator::Now ().GetSeconds()<4.5);
  // Ptr<MobilityModel> mob=stas.Get(0)->GetObject<MobilityModel>();
  // Ptr<MobilityModel> mob2=stas.Get(1)->GetObject<MobilityModel>();
  // double dis2=mob->GetDistanceFrom(mob2);
  std::set<uint32_t> nodecnt;
  std::vector<uint32_t> find_dest[3]; 
  uint32_t k=4;
  uint32_t dest=38;
  Ptr<MobilityModel> mob=vehicles.Get(k)->GetObject<MobilityModel>();
  for(uint32_t j=0;j<50;j++)
    nodecnt.insert(j);
  for(uint32_t i=0;i<50;i++)
  {

      if(i==k)
      continue; 
      Ptr<MobilityModel> mobi=vehicles.Get(i)->GetObject<MobilityModel>();
      double dis1=mobi->GetDistanceFrom(mob);
      if(nodecnt.find(i)!=nodecnt.end())
      {
        if(dis1<=stnd)
       {
         std::cout<<"KCH toh hua:"<<i<<std::endl; 
        find_dest[0].push_back(i);
        nodecnt.erase(nodecnt.find(i));
       }
      }
  }
  for(uint32_t h=0;h<2;h++)
  {   
      for(uint32_t j=0;j<50;j++)
      {
         Ptr<MobilityModel> mob1=vehicles.Get(j)->GetObject<MobilityModel>();
         if(nodecnt.find(j)==nodecnt.end())
          continue;
         for(uint32_t l=0;l<find_dest[h].size();l++)
         {
              Ptr<MobilityModel> mob2=vehicles.Get(find_dest[h][l])->GetObject<MobilityModel>();
              double dis2=mob1->GetDistanceFrom(mob2);
              if(dis2<=stnd)
              {
                 if(j==dest)
                  std::cout<<"DEST found:mission accomplished"<<std::endl;
                 find_dest[h+1].push_back(j);
                 if(nodecnt.find(j)!=nodecnt.end())
                  nodecnt.erase(nodecnt.find(j));
              }
         }
      }
  }
  // Create all nodes.
  

  // ns2.Install (); // configure movements for each node, while reading trace file

  // Configure callback for logging
  // Config::Connect ("/NodeList/*/$ns3::MobilityModel/CourseChange",
                   // MakeBoundCallback (&CourseChange, &os));
  AnimationInterface anim ("SimpleNS3SimulationWithns2.xml");
  Simulator::Stop (Seconds (duration));
  Simulator::Run ();
  Simulator::Destroy ();

  // os.close (); // close log file
  return 0;
}
